stages:
  - buildFrontend
  - testFrontend
  - deployFrontend

buildFrontend:
  stage: buildFrontend
  script:
    - cd frontend
    - npm install
    - make deps

testFrontend:
  stage: testFrontend
  script:
    - cd frontend
    - npm install
    - npm start &
    - sleep 10
    - chmod +x ../tryKill.sh
    - .././tryKill.sh
    - make run
    - sleep 5
    - docker stop MockAPI
    - docker rm MockAPI

deployFrontend:
  stage: deployFrontend
  environment:
    name: staging
  script:
    - echo $CI_COMMIT_BRANCH
    - ssh toffee@192.168.10.112 "cd ~/frontendDeployment/ && sudo rm -r dogecoin-testnet-faucet && git clone git@gitlab.com:toffee_/dogecoin-testnet-faucet.git && cd dogecoin-testnet-faucet && git checkout $CI_COMMIT_BRANCH && git pull && chmod +x tryKill.sh && ./tryKill.sh && cd frontend && npm install && screen -dm npm start && docker restart MockAPI"