stages:
  - buildFrontend
  - testFrontend
  - deployFrontend

buildFrontend:
  stage: buildFrontend
  script:
    - cd frontend
    - npm install
    - make deps

testFrontend:
  stage: testFrontend
  script:
    - cd frontend
    - npm start &
    - sleep 10
    - chmod +x ../tryKill.sh
    - .././tryKill.sh
    - make run &
    - docker stop $(docker ps -aq)
    - docker rm $(docker ps –aq)

deployFrontend:
  stage: deployFrontend
  script:
    - echo "Not set up just yet."