stages:
  - buildFrontend
  - testFrontend
  - deployPrep
  - deployFrontend

buildFrontend:
  stage: buildFrontend
  script:
    - cd frontend
    - npm install
    - make deps

testFrontend:
  stage: testFrontend
  script:
    - cd frontend
    - npm install
    - npm start &
    - sleep 10
    - chmod +x ../tryKill.sh
    - .././tryKill.sh
    - make run
    - sleep 5
    - docker stop MockAPI
    - docker rm MockAPI

deployPrep:
  stage: deployPrep
  script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

deployFrontend:
  stage: deployFrontend
  environment:
    name: staging
  script:
    - ssh toffee@192.168.10.112 "cd ~/frontendDeployment/dogecoin-testnet-faucet && git pull && chmod +x tryKill.sh && ./tryKill.sh && cd frontend && npm install && npm start & && docker restart MockAPI"