stages:
  - buildFrontend
  - testFrontend
  - deployFrontend

buildFrontend:
  stage: buildFrontend
  script:
    - cd frontend
    - npm install
    - make deps

testFrontend:
  stage: testFrontend
  script:
    - cd frontend
    - npm install
    - npm start &
    - sleep 10
    - chmod +x ../tryKill.sh
    - .././tryKill.sh
    - make run &
    - sleep 5
    - docker stop MockAPI
    - screen docker rm MockAPI

deployFrontend:
  stage: deployFrontend
  script:
    - echo "Not set up just yet."